services:
  - type: web
    name: garden-constr
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend && pip install -r requirements.txt && cd ../frontend && npm install && DISABLE_ESLINT_PLUGIN=true npm run build
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
